services:
  castafiore-headless:
    image: cstaelen/castafiore-headless:latest
    devices:
      - /dev/snd
    ports:
      - "8899:8899"
    volumes:
      - ./config:/config   # place camilladsp.yml here to override default config
      - mpd_data:/var/lib/mpd
    restart: unless-stopped

volumes:
  mpd_data:
