music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"
log_file "/var/log/mpd.log"
state_file "/var/lib/mpd/state"
bind_to_address "127.0.0.1"

audio_output {
    type "fifo"
    name "CamillaDSP pipe"
    path "/tmp/mpd.fifo"
    format "48000:32:2"
}
